# docker-compose.yml

services:
  backend:
    build: ./backend                # Usa por defecto ./backend/Dockerfile
    container_name: api-task-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./storage:/app/storage
      - ./.env:/app/.env:ro
      - ./.env.example:/app/.env.example:ro
    env_file:
      - .env.example
      - .env
    environment:
      - POSTGRES_HOST=postgres  # Override para usar el nombre del servicio
      - MYSQL_HOST=mysql
    depends_on:
      postgres:
        condition: service_healthy  # Espera hasta que PostgreSQL esté listo
      mysql:
        condition: service_healthy
    networks:
      - backend-db
    restart: unless-stopped  # Auto-reiniciar si falla

  postgres:
    image: postgres:17-alpine
    container_name: task-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.example
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-db
    restart: unless-stopped

  mysql:
      image: mysql:8.0-debian
      container_name: task-mysql
      ports:
        - "3307:3306" # Map de puerto en caso de estar ocupado
      env_file:
        - .env.example
        - .env
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
        - mysql_data:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
        interval: 2s
        timeout: 5s
        retries: 10
        start_period: 30s
      networks:
        - backend-db
      restart: unless-stopped

volumes:
  postgres_data:
  mysql_data:

networks:
  backend-db:
    driver: bridge